Resources:
  pineappleCheckLambdaHandlerServiceRoleFC4E3211:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: TheStateMachineStack/pineappleCheckLambdaHandler/ServiceRole/Resource
  pineappleCheckLambdaHandlerFDB742D5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: be435508c5c4d6167e0286f4e21327bae34c8d645f732c6dad9c6c1dcd2e5987.zip
      Role:
        Fn::GetAtt:
          - pineappleCheckLambdaHandlerServiceRoleFC4E3211
          - Arn
      Handler: orderPizza.handler
      Runtime: nodejs18.x
    DependsOn:
      - pineappleCheckLambdaHandlerServiceRoleFC4E3211
    Metadata:
      aws:cdk:path: TheStateMachineStack/pineappleCheckLambdaHandler/Resource
      aws:asset:path: asset.be435508c5c4d6167e0286f4e21327bae34c8d645f732c6dad9c6c1dcd2e5987
      aws:asset:is-bundled: false
      aws:asset:property: Code
  StateMachineRoleB840431D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/Resource
  StateMachineRoleDefaultPolicyDF1E6607:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
              - xray:PutTelemetryRecords
              - xray:PutTraceSegments
            Effect: Allow
            Resource: "*"
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - pineappleCheckLambdaHandlerFDB742D5
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - pineappleCheckLambdaHandlerFDB742D5
                        - Arn
                    - :*
        Version: "2012-10-17"
      PolicyName: StateMachineRoleDefaultPolicyDF1E6607
      Roles:
        - Ref: StateMachineRoleB840431D
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Role/DefaultPolicy/Resource
  StateMachine2E01A3A5:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
          - StateMachineRoleB840431D
          - Arn
      DefinitionString:
        Fn::Join:
          - ""
          - - '{"StartAt":"Order Pizza Job","States":{"Order Pizza Job":{"Next":"With Pineapple?","Retry":[{"ErrorEquals":["Lambda.ServiceException","Lambda.AWSLambdaException","Lambda.SdkClientException"],"IntervalSeconds":2,"MaxAttempts":6,"BackoffRate":2}],"Type":"Task","InputPath":"$.flavour","ResultPath":"$.pineappleAnalysis","Resource":"'
            - Fn::GetAtt:
                - pineappleCheckLambdaHandlerFDB742D5
                - Arn
            - '"},"With Pineapple?":{"Type":"Choice","Choices":[{"Variable":"$.pineappleAnalysis.containsPineapple","BooleanEquals":true,"Next":"Sorry, We Dont add Pineapple"}],"Default":"Lets make your pizza"},"Lets make your pizza":{"Type":"Succeed","OutputPath":"$.pineappleAnalysis"},"Sorry, We Dont add Pineapple":{"Type":"Fail","Error":"Failed To Make Pizza","Cause":"They asked for Pineapple"}},"TimeoutSeconds":300}'
      StateMachineType: EXPRESS
      TracingConfiguration:
        Enabled: true
    DependsOn:
      - StateMachineRoleDefaultPolicyDF1E6607
      - StateMachineRoleB840431D
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: TheStateMachineStack/StateMachine/Resource
  HttpApiRole79B5C31A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action: states:StartSyncExecution
                Effect: Allow
                Resource:
                  Ref: StateMachine2E01A3A5
            Version: "2012-10-17"
          PolicyName: AllowSFNExec
    Metadata:
      aws:cdk:path: TheStateMachineStack/HttpApiRole/Resource
  thestatemachineapi69C81CC4:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: the-state-machine-api
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/Resource
  thestatemachineapiDefaultStageE23A2C15:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      StageName: $default
      AutoDeploy: true
    Metadata:
      aws:cdk:path: TheStateMachineStack/the-state-machine-api/DefaultStage/Resource
  Integ:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      IntegrationType: AWS_PROXY
      ConnectionType: INTERNET
      CredentialsArn:
        Fn::GetAtt:
          - HttpApiRole79B5C31A
          - Arn
      IntegrationSubtype: StepFunctions-StartSyncExecution
      PayloadFormatVersion: "1.0"
      RequestParameters:
        Input: $request.body
        StateMachineArn:
          Ref: StateMachine2E01A3A5
      TimeoutInMillis: 10000
    Metadata:
      aws:cdk:path: TheStateMachineStack/Integ
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: thestatemachineapi69C81CC4
      RouteKey: $default
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: Integ
    Metadata:
      aws:cdk:path: TheStateMachineStack/DefaultRoute
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/12Q3W7CMAyFn4X71PxM2rgcIE1D2rSpPAAyqSmmJamIA0JR331JKBLa1fFxPtknnsH8DcJkhFdX6KopWt5B2AjqRsXWNrR42lUI4cMbLWyNWu3No+4V4wlCaVtK7ay/tmV9S/Ze9cq9bNE5EgeLJNHD0uuGZImOlBPq9sM8txV0jYOvvHNtLrb5B8QcyK3aeK2JKrU6WNakYlyhb9QHNjnIs+8VdlxHf8XbZQYhPi86Hqg642sjVJ/x8bvSeqG+VyU5689xfI6daDZ1An68dF4y+kBivbKm4vtVJgW23QFhMnofzjpO+hxkIMKnSJfyJM2B4mJjK4KjG1+mrzCdxylHx1ycvRE+EZR3/QNrGVOguAEAAA==
    Metadata:
      aws:cdk:path: TheStateMachineStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  HTTPAPIUrl:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: thestatemachineapi69C81CC4
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2